name: Example testing
on:
    push:
        branches:
            - example
            - main
jobs:
    testing-job:
        - name: install flake8
          runs-on: "ubuntu-latest"
        steps:
            run: apt install -y flake8
            run: flake8 simple_function.py
            run: python simple_function.py
            run: python script.py

