name: Example testing
on:
    push:
        branches:
            - example
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - name: runinng
          run: python simple_function.py
        - name: run script
          run: python script.py

