name: Example testing
on:
    push:
        branches:
            - example
jobs:
    testin_job:
            - name: install flake8
              runs-on: ubuntu-latest
              steps:
                - name: Git checkout
                  uses:action/checkout@v4
                - name: Install
                  run: apt install -y flake8
                - name: flake8
                  run: flake8 simple_function.py
                - name: runinng
                  run: python simple_function.py
                - name: run script
                  run: python script.py

