name: Example testing
on:
    push:
        branches:
            - main
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - name: Get Code
          uses: actions/checkout@v4
        - name: runinng
          run: python simple_functions.py
        - name: run script
          run: python script.py

