name: Python Package
on:
    push:
        branches:
            - main
jobs:
    build:
        runs-on: ubuntu-latest
        defaults:
            run:
                shell: bash -el {0}
        steps:
             - name: Checkout Repo
               uses: actions/checkout@v4
             - name: Setup Miniconda
               uses: conda-incubator/setup-miniconda@v3
               with:
                 activate-environment: mle-dev
                 environment-file: env.yml
                 auto-activate-base: false
             - run: |
                    sudo apt install tree
             - name: before
               run: tree
             - name: Build package
               run: python -m build
             - name: Display after
               run: tree
             - uses: actions/upload-artifact@v4
               with:
                  name: art1
                  path: dist/

